version: '3.0'
services:
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - '1234:1234'
      - '26162:26162'
    # command: sh -c "rm -f tmp/pids/server.pid && bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s -p 3000 -b '0.0.0.0'"
    # depends_on:
    #  - db
    tty: true
    stdin_open: true
  # db:
  #  image: mysql:5.7
  #  volumes:
  #    - db-volume:/var/lib/mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: password
# volumes:
#  db-volume:
  selenium_chrome:
    # image: seleniarm/standalone-chromium
    image: seleniarm/standalone-chromium:latest
    logging:
      driver: none

  api-mock:
    image: danielgtaylor/apisprout
    ports:
      - 8010:8000
    volumes:
      - ./dest/merged.yaml:/merged.yaml
    entrypoint: /usr/local/bin/apisprout /merged.yaml --watch

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "10081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "10082:8080"
    volumes:
      - ./dest/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      API_URL: merged.yaml
  swagger-api:
    image: stoplight/prism:3
    ports:
      - "10083:4010"
    command: mock -h 0.0.0.0 /dest/openapi/openapi.yaml
    volumes:
      - ./dest:/dest
  redoc:
    image: redocly/redoc
    ports:
      - 9011:80
    volumes:
      - ./dest/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      SPEC_URL: merged.yaml
  redoc-cli:
    build: ./docker/redoc-cli
    volumes:
      - ./src:/src
      - ./dest:/dest
  swagger-merger:
    build: ./docker/swagger-merger
    command: >
      watch 'swagger-merger -i /src/index.yaml -o /dest/merged.yaml' /src/
    volumes:
      - ./src:/src
      - ./dest:/dest
    environment:
      NODE_PATH: /usr/local/lib/node_modules
    # entrypoint: node ../watch
